"""
Generate ``static/css/src/dropcaps.css`` from the dropcap style registry.

The stylesheet is committed so the frontend build stays a plain PostCSS
run, but it is derived: edit ``engine/markdown/dropcaps.py`` and rerun
this command. ``--check`` exits non-zero when the committed file is stale
(the test suite runs it).

Mechanics, all keyed on inherited CSS custom properties so the nearest
ancestor wins:

* ``.markdownBody.dropcap-<key>`` (from the post/page/site setting) and
  ``p.dropcap-<key>`` (from a ``::: {.dropcap-<key>}`` block) set
  ``--dropcap-font`` and friends.
* ``p.dropcap .dropcap-letter`` reads them. With none set the span is an
  ordinary inline span, which is how the same cached HTML renders with or
  without a dropcap.
"""

from __future__ import annotations

from pathlib import Path

from django.conf import settings
from django.core.management.base import BaseCommand, CommandError

from engine.markdown import dropcaps

UNICODE_RANGE = "U+0030-0039, U+0041-005A, U+0061-007A, U+00C0-00D6, U+00D8-00DE"

HEADER = """/*  Dropcaps.
 *
 *  GENERATED by `manage.py generate_dropcaps_css` from
 *  engine/markdown/dropcaps.py — edit the registry, not this file.
 *
 *  Markup (from dropcap_enhancer.py): the opening paragraph of a document,
 *  and any paragraph wrapped in ::: {.dropcap-<key>}, becomes
 *    p.dropcap[.dropcap-<key>] > span.dropcap-letter
 *  with an optional span.dropcap-punct inside for an opening quote.
 *  The style comes from custom properties set on the .markdownBody wrapper
 *  (document setting) or on the paragraph itself (block override); the
 *  nearest ancestor wins. Without either, the span is inert.
 */
"""

BASE_RULES = """
/*  Only used-on-page faces are fetched: unicode-range gates the download. */

/*  A floated letter rather than `initial-letter`: Chrome only applies that
 *  property to ::first-letter, not to an inline span, and a single float
 *  path renders the same in every browser. Geometry, for a face with cap
 *  height ~0.7em:
 *  the cap must run from the first line's cap line to the third line's
 *  baseline, i.e. (N - 1) lines + one body cap height ≈ N × line-height ×
 *  1.18 of body size. line-height 0.8 tightens the box to roughly the cap,
 *  and the margins seat the cap on the first line without pushing a fourth
 *  line aside. --dropcap-scale / --dropcap-nudge tune faces whose metrics
 *  differ.
 */
.markdownBody p.dropcap .dropcap-letter {
  font-family: var(--dropcap-font, inherit);
  font-weight: var(--dropcap-weight, inherit);
  font-style: normal;
  font-variant-caps: normal;
  float: var(--dropcap-float, none);
  font-size: calc(
    var(--dropcap-lines, 3) * var(--dropcap-line-height, 1.5) *
      var(--dropcap-scale, 1) * var(--dropcap-fit, 1.18) * 1em
  );
  line-height: 0.8;
  margin: calc(0.07em + var(--dropcap-nudge, 0em)) var(--dropcap-gap, 0.1em)
    -0.06em 0;
  padding: 0;
  color: var(--dropcap-color, inherit);
}

.markdownBody p.dropcap .dropcap-letter .dropcap-punct {
  font-family: var(--AT-serif-font-stack);
  font-weight: 400;
  font-size: 0.45em;
  line-height: 1;
  vertical-align: top;
  margin-right: 0.05em;
}

/*  Shorter drops on phones; an explicit `lines=` on a block still wins
 *  because it is an inline style on the paragraph.
 */
@media all and (max-width: 649px) {
  .markdownBody p.dropcap {
    --dropcap-lines: 2;
  }
}

@media print {
  .markdownBody p.dropcap .dropcap-letter {
    color: #000;
  }
}
"""


def render_css() -> str:
    parts = [HEADER]

    parts.append("\n/*  Faces, subset to Latin letters and digits. */\n")
    for style in dropcaps.STYLES:
        weight = "100 900" if style.variable else str(style.weight)
        parts.append(
            "@font-face {\n"
            f"  font-family: '{style.family}';\n"
            f"  font-weight: {weight};\n"
            "  font-style: normal;\n"
            f"  src: url('{style.font_path}') format('woff2');\n"
            "  font-display: swap;\n"
            f"  unicode-range: {UNICODE_RANGE};\n"
            "}\n"
        )

    parts.append(BASE_RULES)

    parts.append(
        "\n/*  Styles: wrapper selector for the document setting, paragraph selector\n"
    )
    parts.append(" *  for a block override.\n */\n")
    on_selectors = []
    for style in dropcaps.STYLES:
        on_selectors.append(f".markdownBody.{style.css_class}")
        on_selectors.append(f".markdownBody p.{style.css_class}")
    parts.append(",\n".join(on_selectors) + " {\n  --dropcap-float: left;\n}\n")

    for style in dropcaps.STYLES:
        decls = [
            f"  --dropcap-font: '{style.family}';",
            f"  --dropcap-weight: {style.weight};",
        ]
        if style.scale != 1.0:
            decls.append(f"  --dropcap-scale: {style.scale:g};")
        if style.nudge:
            decls.append(f"  --dropcap-nudge: {style.nudge:g}em;")
        if style.gap != 0.1:
            decls.append(f"  --dropcap-gap: {style.gap:g}em;")
        parts.append(
            f"\n/* {style.label} — {style.license} */\n"
            f".markdownBody.{style.css_class},\n"
            f".markdownBody p.{style.css_class} {{\n" + "\n".join(decls) + "\n}\n"
        )

    return "".join(parts)


def target_path() -> Path:
    return Path(settings.BASE_DIR) / "static" / "css" / "src" / "dropcaps.css"


class Command(BaseCommand):
    help = "Write static/css/src/dropcaps.css from the dropcap style registry."

    def add_arguments(self, parser):
        parser.add_argument(
            "--check",
            action="store_true",
            help="Do not write; fail if the committed stylesheet is out of date.",
        )

    def handle(self, *args, **options):
        css = render_css()
        path = target_path()
        if options["check"]:
            current = path.read_text() if path.exists() else ""
            if current != css:
                raise CommandError(
                    f"{path.relative_to(settings.BASE_DIR)} is out of date; run "
                    "`manage.py generate_dropcaps_css` and commit the result."
                )
            self.stdout.write("dropcaps.css is up to date.")
            return
        path.write_text(css)
        self.stdout.write(
            f"Wrote {path.relative_to(settings.BASE_DIR)} "
            f"({len(dropcaps.STYLES)} styles)."
        )
