"""
Django settings for ATProject project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

import environ

env = environ.Env(
    # set casting, default value
    DEBUG=(bool, False),
    # DB settings
    DB_CONN_MAX_AGE=(int, 60),  # persistent connections (seconds)
    DB_HEALTH_CHECKS=(bool, True),  # ping the DB when reusing connections (Django 4.2+)
    DB_USE_ATOMIC_REQUESTS=(
        bool,
        False,
    ),  # wrap each request in a transaction (trade-off below)
    DB_SSL_REQUIRE=(bool, True),  # force TLS if your DB supports it
    DB_CONNECT_TIMEOUT_S=(int, 5),  # fail fast on bad networks
    DB_STATEMENT_TIMEOUT_MS=(int, 15000),  # kill slow queries (15s)
    DB_IDLE_TX_TIMEOUT_MS=(int, 10000),  # kill stuck idle-in-tx sessions (10s)
    DB_LOCK_TIMEOUT_MS=(int, 2000),  # fail fast on lock waits (2s)
    DB_APP_NAME=(str, "django-app"),  # tag connections in pg_stat_activity
    DB_TARGET_SESSION_ATTRS=(
        str,
        "read-write",
    ),  # avoid accidentally hitting read-only endpoints
    DB_DISABLE_SERVER_SIDE_CURSORS=(
        bool,
        False,
    ),  # set True for PgBouncer (txn pooling)
    # R2 / S3 params
    R2_ACCESS_KEY_ID=(str, ""),
    R2_SECRET_ACCESS_KEY=(str, ""),
    R2_BUCKET_NAME=(str, ""),
    R2_S3_ENDPOINT_URL=(str, ""),  # https://<ACCOUNT_ID>.r2.cloudflarestorage.com
    R2_REGION=(str, "auto"),
    R2_SIG_VERSION=(str, "s3v4"),
    R2_ADDRESSING_STYLE=(str, "path"),
    # URL behavior
    R2_SIGNED_URLS=(bool, False),  # False => public URLs; True => signed URLs
    R2_CUSTOM_DOMAIN=(
        str,
        "",
    ),  # e.g., cdn.example.com OR pub-xxxx.r2.dev (leave blank for private)
    # Caching
    R2_CACHE_CONTROL=(str, "public, max-age=31536000, immutable"),
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
environ.Env.read_env(os.path.join(BASE_DIR, ".env"))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG")

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=[])

# Railway provides RAILWAY_PUBLIC_DOMAIN for the app's domain
RAILWAY_PUBLIC_DOMAIN = env("RAILWAY_PUBLIC_DOMAIN", default=None)
if RAILWAY_PUBLIC_DOMAIN:
    ALLOWED_HOSTS.append(RAILWAY_PUBLIC_DOMAIN)

# Railway health checks use this host
ALLOWED_HOSTS.append("healthcheck.railway.app")

# CSRF trusted origins for Railway and custom domains
CSRF_TRUSTED_ORIGINS = env.list("CSRF_TRUSTED_ORIGINS", default=[])
if RAILWAY_PUBLIC_DOMAIN:
    CSRF_TRUSTED_ORIGINS.append(f"https://{RAILWAY_PUBLIC_DOMAIN}")

ADMINS = env.list("ADMINS", default=[])

# ==============================================================================
# SECURITY SETTINGS (PRODUCTION)
# ==============================================================================

if not DEBUG:
    # --- SSL / HTTPS ---
    # Trust X-Forwarded-Proto header from Cloudflare/Railway proxy
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = env.bool("DJANGO_SECURE_SSL_REDIRECT", default=True)
    SESSION_COOKIE_SECURE = env.bool("DJANGO_SESSION_COOKIE_SECURE", default=True)
    CSRF_COOKIE_SECURE = env.bool("DJANGO_CSRF_COOKIE_SECURE", default=True)

    # --- HSTS (HTTP Strict Transport Security) ---
    # Manually enable this after confirming your site works perfectly over HTTPS.
    # Start with a small value (e.g., 3600) and gradually increase.
    SECURE_HSTS_SECONDS = env.int("DJANGO_SECURE_HSTS_SECONDS", default=0)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = env.bool(
        "DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS", default=True
    )
    SECURE_HSTS_PRELOAD = env.bool("DJANGO_SECURE_HSTS_PRELOAD", default=True)

    # --- Other Security Headers ---
    # Modern browsers have deprecated XSS protection in favor of strong Content
    # Security Policy (CSP), which should be configured separately.
    # SECURE_BROWSER_XSS_FILTER is True by default in Django 5 but will be removed.
    SECURE_CONTENT_TYPE_NOSNIFF = env.bool(
        "DJANGO_SECURE_CONTENT_TYPE_NOSNIFF", default=True
    )

# ==============================================================================
# CONTENT SECURITY POLICY (django-csp 4.0+)
# https://django-csp.readthedocs.io/en/latest/configuration.html
# ==============================================================================

# Base CSP directives (R2 domain added dynamically below)
_CSP_IMG_SRC = ["'self'", "data:"]
_CSP_MEDIA_SRC = ["'self'"]

# Shared CSP directives
_CSP_DIRECTIVES = {
    "default-src": ["'self'"],
    # MathJax requires 'unsafe-inline' for dynamic script creation
    "script-src": ["'self'", "'unsafe-inline'", "https://cdn.jsdelivr.net", "https://static.cloudflareinsights.com"],
    # MathJax requires 'unsafe-inline' for dynamic styles
    "style-src": ["'self'", "'unsafe-inline'"],
    "font-src": ["'self'"],
    "img-src": _CSP_IMG_SRC,
    "media-src": _CSP_MEDIA_SRC,
    "connect-src": ["'self'", "https://cloudflareinsights.com"],
    "form-action": ["'self'"],
    "frame-ancestors": ["'self'"],
    "base-uri": ["'self'"],
}

# Enforced policy (production) or report-only (development)
if DEBUG:
    CONTENT_SECURITY_POLICY_REPORT_ONLY = {"DIRECTIVES": _CSP_DIRECTIVES}
else:
    CONTENT_SECURITY_POLICY = {"DIRECTIVES": _CSP_DIRECTIVES}


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "engine",
]

# THIRD-PARTY APPS
INSTALLED_APPS += [
    # Optional: enable result/beat Django apps
    "django_celery_results",
    "django_celery_beat",
    "storages",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "csp.middleware.CSPMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "ATProject.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


WSGI_APPLICATION = "ATProject.wsgi.application"

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# PostgreSQL Database Configuration
# Requires DATABASE_URL environment variable (Railway/Neon format)
# Example: postgresql://user:password@host:5432/dbname?sslmode=require
if not env("DATABASE_URL", default=None):
    raise environ.ImproperlyConfigured(
        "DATABASE_URL environment variable is required. "
        "Set it in Railway dashboard or .env file."
    )
DATABASES = {"default": env.db("DATABASE_URL")}

# ---- Recommended tweaks ----
db = DATABASES["default"]

# 1) Connection reuse & health
# For Neon serverless: use shorter CONN_MAX_AGE (0-60s) as connections may be recycled
db["CONN_MAX_AGE"] = env.int("DB_CONN_MAX_AGE")  # e.g. 60s in prod, 0 in dev/tests
db["CONN_HEALTH_CHECKS"] = env.bool(
    "DB_HEALTH_CHECKS"
)  # ping on reuse to avoid stale sockets

# 2) Safety/ergonomics per request
db["ATOMIC_REQUESTS"] = env.bool("DB_USE_ATOMIC_REQUESTS")  # see notes below

# 3) Neon serverless / PgBouncer compatibility
# When using Neon's pooled connection endpoint (-pooler), disable server-side cursors
db["DISABLE_SERVER_SIDE_CURSORS"] = env.bool("DB_DISABLE_SERVER_SIDE_CURSORS")

# 4) Driver / libpq options
db.setdefault("OPTIONS", {})
db["OPTIONS"].update(
    {
        # libpq keyword args (preferred where available)
        "sslmode": "require" if env.bool("DB_SSL_REQUIRE") else "prefer",
        "connect_timeout": env.int("DB_CONNECT_TIMEOUT_S"),
        "application_name": env.str("DB_APP_NAME"),
        "target_session_attrs": env.str("DB_TARGET_SESSION_ATTRS"),
    }
)

# 5) Neon-specific: Add endpoint ID for SNI routing if provided
# Only needed for DIRECT connections (not pooler URLs which have -pooler in hostname)
# Pooler URLs already include endpoint info in the hostname
NEON_ENDPOINT_ID = env("NEON_ENDPOINT_ID", default=None)
DATABASE_URL = env("DATABASE_URL", default="")
if NEON_ENDPOINT_ID and "-pooler" not in DATABASE_URL:
    db["OPTIONS"]["options"] = f"-c endpoint={NEON_ENDPOINT_ID}"


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "America/New_York"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
# For Whitenoise
STATIC_ROOT = BASE_DIR / "staticfiles"

# Only in development
if DEBUG:
    WHITENOISE_USE_FINDERS = True

# WhiteNoise (optional but recommended if static is local)
if "whitenoise.middleware.WhiteNoiseMiddleware" in MIDDLEWARE:
    STORAGES = {
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
        "default": {  # media on R2 (set below)
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        },
    }
else:
    STORAGES = {
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
        "default": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        },
    }

# ---- R2 / django-storages (media) ----
AWS_ACCESS_KEY_ID = env("R2_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = env("R2_SECRET_ACCESS_KEY")
AWS_STORAGE_BUCKET_NAME = env("R2_BUCKET_NAME")
AWS_S3_ENDPOINT_URL = env("R2_S3_ENDPOINT_URL")
AWS_S3_REGION_NAME = env("R2_REGION")
AWS_S3_SIGNATURE_VERSION = env("R2_SIG_VERSION")
AWS_S3_ADDRESSING_STYLE = env("R2_ADDRESSING_STYLE")
AWS_DEFAULT_ACL = None

# Build URL behavior from env flags
AWS_S3_CUSTOM_DOMAIN = env("R2_CUSTOM_DOMAIN") or None
AWS_QUERYSTRING_AUTH = env.bool("R2_SIGNED_URLS")

# Default to signed URLs when no public domain is configured (R2 buckets are private by default)
if AWS_S3_CUSTOM_DOMAIN is None and not AWS_QUERYSTRING_AUTH:
    AWS_QUERYSTRING_AUTH = True

# Set Cache-Control on objects
AWS_S3_OBJECT_PARAMETERS = {"CacheControl": env("R2_CACHE_CONTROL")}

# MEDIA_URL:
# - Public: use the custom domain (r2.dev or your domain)
# - Private: MEDIA_URL is a placeholder; actual URLs are signed when calling file.url
if AWS_S3_CUSTOM_DOMAIN:
    MEDIA_URL = f"https://{AWS_S3_CUSTOM_DOMAIN.rstrip('/')}/"
    # Add R2 custom domain to CSP for images and media
    _CSP_IMG_SRC.append(f"https://{AWS_S3_CUSTOM_DOMAIN}")
    _CSP_MEDIA_SRC.append(f"https://{AWS_S3_CUSTOM_DOMAIN}")
elif AWS_S3_ENDPOINT_URL:
    MEDIA_URL = f"{AWS_S3_ENDPOINT_URL.rstrip('/')}/{AWS_STORAGE_BUCKET_NAME}/"
    # Add R2 endpoint to CSP for images and media (signed URLs)
    _CSP_IMG_SRC.append(AWS_S3_ENDPOINT_URL.rstrip("/"))
    _CSP_MEDIA_SRC.append(AWS_S3_ENDPOINT_URL.rstrip("/"))
else:
    MEDIA_URL = f"https://{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com/"

# # Dev ergonomics: keep media local if you prefer
# if DEBUG and env.bool("USE_LOCAL_MEDIA_IN_DEV", default=False):
#     STORAGES["default"] = {"BACKEND": "django.core.files.storage.FileSystemStorage"}
#     MEDIA_URL = "/media/"
#     MEDIA_ROOT = BASE_DIR / "media"

# # Media files (User uploads)
# MEDIA_URL = "/media/"
# MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Celery (Redis)
CELERY_BROKER_URL = env("REDIS_URL")
CELERY_RESULT_BACKEND = "django-db"
CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"


# Recommended dev defaults
CELERY_TASK_ALWAYS_EAGER = False  # set True in unit tests
CELERY_TASK_EAGER_PROPAGATES = False
CELERY_TASK_TIME_LIMIT = 60 * 5  # hard limit, seconds
CELERY_TASK_SOFT_TIME_LIMIT = 60 * 4
CELERY_TASK_SERIALIZER = "json"
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_RESULT_EXPIRES = 60 * 60  # 1 hour
CELERY_ENABLE_UTC = True  # Celery reads Django’s TZ too
CELERY_RESULT_EXTENDED = True  # Store meta information for admin inspection


# ==============================================================================
# DJANGO ADMIN CONFIGURATION
# ==============================================================================

# Customize admin site header and title
ADMIN_SITE_HEADER = "Architextual Admin"
ADMIN_SITE_TITLE = "Architextual"
ADMIN_INDEX_TITLE = "Site Administration"
