"""
Django settings for ATProject project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from typing import Literal, Optional

import environ

env = environ.Env(
    # set casting, default value
    DEBUG=(bool, False),
    # DB settings
    DB_CONN_MAX_AGE=(int, 60),  # persistent connections (seconds)
    DB_HEALTH_CHECKS=(bool, True),  # ping the DB when reusing connections (Django 4.2+)
    DB_USE_ATOMIC_REQUESTS=(
        bool,
        False,
    ),  # wrap each request in a transaction (trade-off below)
    DB_SSL_REQUIRE=(bool, True),  # force TLS if your DB supports it
    DB_CONNECT_TIMEOUT_S=(int, 5),  # fail fast on bad networks
    DB_STATEMENT_TIMEOUT_MS=(int, 15000),  # kill slow queries (15s)
    DB_IDLE_TX_TIMEOUT_MS=(int, 10000),  # kill stuck idle-in-tx sessions (10s)
    DB_LOCK_TIMEOUT_MS=(int, 2000),  # fail fast on lock waits (2s)
    DB_APP_NAME=(str, "django-app"),  # tag connections in pg_stat_activity
    DB_TARGET_SESSION_ATTRS=(
        str,
        "read-write",
    ),  # avoid accidentally hitting read-only endpoints
    DB_DISABLE_SERVER_SIDE_CURSORS=(
        bool,
        False,
    ),  # set True for PgBouncer (txn pooling)
    # R2 / S3 params
    R2_ACCESS_KEY_ID=(str, ""),
    R2_SECRET_ACCESS_KEY=(str, ""),
    R2_BUCKET_NAME=(str, ""),
    R2_S3_ENDPOINT_URL=(str, ""),  # https://<ACCOUNT_ID>.r2.cloudflarestorage.com
    R2_REGION=(str, "auto"),
    R2_SIG_VERSION=(str, "s3v4"),
    R2_ADDRESSING_STYLE=(str, "path"),
    # URL behavior
    R2_SIGNED_URLS=(bool, False),  # False => public URLs; True => signed URLs
    R2_CUSTOM_DOMAIN=(
        str,
        "",
    ),  # e.g., cdn.example.com OR pub-xxxx.r2.dev (leave blank for private)
    # Caching
    R2_CACHE_CONTROL=(str, "public, max-age=31536000, immutable"),
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
environ.Env.read_env(os.path.join(BASE_DIR, ".env"))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG")

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS")

ADMINS = env.list("ADMINS")

# Application definition

INSTALLED_APPS = [
    "unfold",  # before django.contrib.admin
    "unfold.contrib.filters",  # optional, if special filters are needed
    "unfold.contrib.forms",  # optional, if special form elements are needed
    "unfold.contrib.inlines",  # optional, if special inlines are needed
    "unfold.contrib.import_export",  # optional, if django-import-export package is used
    "unfold.contrib.guardian",  # optional, if django-guardian package is used
    "unfold.contrib.simple_history",  # optional, if django-simple-history package is used
    "unfold.contrib.location_field",  # optional, if django-location-field package is used
    "unfold.contrib.constance",  # optional, if django-constance package is used
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "engine",
]

# THIRD-PARTY APPS
INSTALLED_APPS += [
    # Optional: enable result/beat Django apps
    "django_celery_results",
    "django_celery_beat",
    "storages",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "ATProject.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


WSGI_APPLICATION = "ATProject.wsgi.application"

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# PostgreSQL Database Configuration
# You can override these with environment variables for different environments
DATABASES = {"default": env.db()}

# ---- Recommended tweaks ----
db = DATABASES["default"]

# 1) Connection reuse & health
db["CONN_MAX_AGE"] = env.int("DB_CONN_MAX_AGE")  # e.g. 60s in prod, 0 in dev/tests
db["CONN_HEALTH_CHECKS"] = env.bool(
    "DB_HEALTH_CHECKS"
)  # ping on reuse to avoid stale sockets

# 2) Safety/ergonomics per request
db["ATOMIC_REQUESTS"] = env.bool("DB_USE_ATOMIC_REQUESTS")  # see notes below

# 3) Driver / libpq options
db.setdefault("OPTIONS", {})
db["OPTIONS"].update(
    {
        # libpq keyword args (preferred where available)
        "sslmode": "require" if env.bool("DB_SSL_REQUIRE") else "prefer",
        "connect_timeout": env.int("DB_CONNECT_TIMEOUT_S"),
        "application_name": env.str("DB_APP_NAME"),
        "target_session_attrs": env.str("DB_TARGET_SESSION_ATTRS"),
    }
)


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "America/New_York"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
# For Whitenoise
STATIC_ROOT = BASE_DIR / "staticfiles"

# Only in development
if DEBUG:
    WHITENOISE_USE_FINDERS = True

# WhiteNoise (optional but recommended if static is local)
if "whitenoise.middleware.WhiteNoiseMiddleware" in MIDDLEWARE:
    STORAGES = {
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
        "default": {  # media on R2 (set below)
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        },
    }
else:
    STORAGES = {
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
        "default": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        },
    }

# ---- R2 / django-storages (media) ----
AWS_ACCESS_KEY_ID = env("R2_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = env("R2_SECRET_ACCESS_KEY")
AWS_STORAGE_BUCKET_NAME = env("R2_BUCKET_NAME")
AWS_S3_ENDPOINT_URL = env("R2_S3_ENDPOINT_URL")
AWS_S3_REGION_NAME = env("R2_REGION")
AWS_S3_SIGNATURE_VERSION = env("R2_SIG_VERSION")
AWS_S3_ADDRESSING_STYLE = env("R2_ADDRESSING_STYLE")
AWS_DEFAULT_ACL = None

# Build URL behavior from env flags
AWS_S3_CUSTOM_DOMAIN = env("R2_CUSTOM_DOMAIN") or None
AWS_QUERYSTRING_AUTH = env.bool("R2_SIGNED_URLS")

# Default to signed URLs when no public domain is configured (R2 buckets are private by default)
if AWS_S3_CUSTOM_DOMAIN is None and not AWS_QUERYSTRING_AUTH:
    AWS_QUERYSTRING_AUTH = True

# Set Cache-Control on objects
AWS_S3_OBJECT_PARAMETERS = {"CacheControl": env("R2_CACHE_CONTROL")}

# MEDIA_URL:
# - Public: use the custom domain (r2.dev or your domain)
# - Private: MEDIA_URL is a placeholder; actual URLs are signed when calling file.url
if AWS_S3_CUSTOM_DOMAIN:
    MEDIA_URL = f"https://{AWS_S3_CUSTOM_DOMAIN.rstrip('/')}/"
elif AWS_S3_ENDPOINT_URL:
    MEDIA_URL = f"{AWS_S3_ENDPOINT_URL.rstrip('/')}/{AWS_STORAGE_BUCKET_NAME}/"
else:
    MEDIA_URL = f"https://{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com/"

# # Dev ergonomics: keep media local if you prefer
# if DEBUG and env.bool("USE_LOCAL_MEDIA_IN_DEV", default=False):
#     STORAGES["default"] = {"BACKEND": "django.core.files.storage.FileSystemStorage"}
#     MEDIA_URL = "/media/"
#     MEDIA_ROOT = BASE_DIR / "media"

# # Media files (User uploads)
# MEDIA_URL = "/media/"
# MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Celery (Redis)
CELERY_BROKER_URL = env("REDIS_URL")
CELERY_RESULT_BACKEND = "django-db"
CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"


# Recommended dev defaults
CELERY_TASK_ALWAYS_EAGER = False  # set True in unit tests
CELERY_TASK_EAGER_PROPAGATES = False
CELERY_TASK_TIME_LIMIT = 60 * 5  # hard limit, seconds
CELERY_TASK_SOFT_TIME_LIMIT = 60 * 4
CELERY_TASK_SERIALIZER = "json"
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_RESULT_EXPIRES = 60 * 60  # 1 hour
CELERY_ENABLE_UTC = True  # Celery reads Django’s TZ too
CELERY_RESULT_EXTENDED = True  # Store meta information for admin inspection


# ==============================================================================
# DJANGO-UNFOLD CONFIGURATION
# ==============================================================================
# Documentation: https://docs.unfoldadmin.com

UNFOLD = {
    # SITE IDENTITY
    "SITE_TITLE": "Architextual Admin",
    "SITE_HEADER": "Architextual",
    "SITE_URL": "/",
    # BRANDING
    # "SITE_LOGO": {
    #     "light": lambda request: static("logo-light.svg"),  # Light theme logo
    #     "dark": lambda request: static("logo-dark.svg"),    # Dark theme logo
    # },
    # "SITE_ICON": {
    #     "light": lambda request: static("icon-light.svg"),  # Favicon for light theme
    #     "dark": lambda request: static("icon-dark.svg"),    # Favicon for dark theme
    # },
    # "SITE_SYMBOL": "speed",  # Material icon name for fallback
    # THEME & COLORS
    "THEME": "light",  # Options: "light", "dark", "auto"
    # Color customization for light theme
    "COLORS": {
        "primary": {
            "50": "248 250 252",  # slate-50
            "100": "241 245 249",  # slate-100
            "200": "226 232 240",  # slate-200
            "300": "203 213 225",  # slate-300
            "400": "148 163 184",  # slate-400
            "500": "100 116 139",  # slate-500
            "600": "71 85 105",  # slate-600 (primary color)
            "700": "51 65 85",  # slate-700
            "800": "30 41 59",  # slate-800
            "900": "15 23 42",  # slate-900
            "950": "2 6 23",  # slate-950
        },
    },
    # SIDEBAR
    "SIDEBAR": {
        "show_search": True,  # Show search in sidebar
        "show_all_applications": True,  # Show all apps or only those with models
        "navigation": [
            {
                "title": "Posts",
                "separator": True,
                "collapsible": False,
                "items": [
                    {
                        "title": "List Posts",
                        "icon": "article",
                        "link": lambda request: "/admin/engine/post/",
                        "badge": "engine.Post",
                    },
                    {
                        "title": "New Post",
                        "icon": "add_circle",
                        "link": lambda request: "/admin/engine/post/add/",
                    },
                ],
            },
            {
                "title": "Assets",
                "separator": True,
                "collapsible": False,
                "items": [
                    {
                        "title": "List Assets",
                        "icon": "image",
                        "link": lambda request: "/admin/engine/asset/",
                        "badge": "engine.Asset",
                    },
                    {
                        "title": "New Asset",
                        "icon": "add_photo_alternate",
                        "link": lambda request: "/admin/engine/asset/add/",
                    },
                ],
            },
            {
                "title": "Post Taxonomy",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "Categories",
                        "icon": "folder",
                        "link": lambda request: "/admin/engine/category/",
                    },
                    {
                        "title": "Tags",
                        "icon": "label",
                        "link": lambda request: "/admin/engine/tag/",
                    },
                    {
                        "title": "Series",
                        "icon": "view_list",
                        "link": lambda request: "/admin/engine/series/",
                    },
                ],
            },
            {
                "title": "Asset Taxonomy",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "Folders",
                        "icon": "folder_open",
                        "link": lambda request: "/admin/engine/assetfolder/",
                    },
                    {
                        "title": "Tags",
                        "icon": "local_offer",
                        "link": lambda request: "/admin/engine/assettag/",
                    },
                    {
                        "title": "Collections",
                        "icon": "collections",
                        "link": lambda request: "/admin/engine/assetcollection/",
                    },
                ],
            },
            {
                "title": "System",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "Users",
                        "icon": "people",
                        "link": lambda request: "/admin/auth/user/",
                    },
                    {
                        "title": "Groups",
                        "icon": "group",
                        "link": lambda request: "/admin/auth/group/",
                    },
                ],
            },
            {
                "title": "Task Queue",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "Periodic Tasks",
                        "icon": "schedule",
                        "link": lambda request: "/admin/django_celery_beat/periodictask/",
                        "badge": "django_celery_beat.PeriodicTask",
                    },
                    {
                        "title": "Interval Schedules",
                        "icon": "timer",
                        "link": lambda request: "/admin/django_celery_beat/intervalschedule/",
                    },
                    {
                        "title": "Crontab Schedules",
                        "icon": "calendar_month",
                        "link": lambda request: "/admin/django_celery_beat/crontabschedule/",
                    },
                    {
                        "title": "Solar Schedules",
                        "icon": "wb_sunny",
                        "link": lambda request: "/admin/django_celery_beat/solarschedule/",
                    },
                    {
                        "title": "Clocked Schedules",
                        "icon": "schedule_send",
                        "link": lambda request: "/admin/django_celery_beat/clockedschedule/",
                    },
                    {
                        "title": "Task Results",
                        "icon": "fact_check",
                        "link": lambda request: "/admin/django_celery_results/taskresult/",
                        "badge": "django_celery_results.TaskResult",
                    },
                    {
                        "title": "Group Results",
                        "icon": "playlist_add_check",
                        "link": lambda request: "/admin/django_celery_results/groupresult/",
                    },
                ],
            },
        ],
    },
    # TABS
    "TABS": [
        {
            "models": [
                "engine.post",
            ],
            "items": [
                {
                    "title": "Posts",
                    "icon": "article",
                    "link": lambda request: "/admin/engine/post/",
                },
                {
                    "title": "Categories",
                    "icon": "folder",
                    "link": lambda request: "/admin/engine/category/",
                },
                {
                    "title": "Tags",
                    "icon": "label",
                    "link": lambda request: "/admin/engine/tag/",
                },
            ],
        },
        {
            "models": [
                "engine.asset",
            ],
            "items": [
                {
                    "title": "All Assets",
                    "icon": "image",
                    "link": lambda request: "/admin/engine/asset/",
                },
                {
                    "title": "Images",
                    "icon": "photo",
                    "link": lambda request: "/admin/engine/asset/?asset_type__exact=image",
                },
                {
                    "title": "Videos",
                    "icon": "videocam",
                    "link": lambda request: "/admin/engine/asset/?asset_type__exact=video",
                },
                {
                    "title": "Documents",
                    "icon": "description",
                    "link": lambda request: "/admin/engine/asset/?asset_type__exact=document",
                },
            ],
        },
    ],
    # ENVIRONMENT BADGE (useful for staging/production)
    "ENVIRONMENT": "ATProject.settings.unfold_environment_callback",
    # Optional: also prefix the <title> tag with the environment
    "ENVIRONMENT_TITLE_PREFIX": "ATProject.settings.unfold_title_prefix_callback",
}

UnfoldColor = Literal["info", "danger", "warning", "success"]

ENV_LABEL: str = env("UNFOLD_ENVIRONMENT")  # type: ignore

COLOR_MAP: dict[str, UnfoldColor] = {
    "PROD": "danger",
    "PRODUCTION": "danger",
    "STAGING": "warning",
    "PREVIEW": "info",
    "DEV": "success",
    "DEVELOPMENT": "success",
}


def unfold_environment_callback(request) -> Optional[tuple[str, UnfoldColor]]:
    if not ENV_LABEL:
        return None
    color: UnfoldColor = COLOR_MAP[ENV_LABEL] if ENV_LABEL in COLOR_MAP else "info"
    return (ENV_LABEL.title(), color)


def unfold_title_prefix_callback(request) -> str:
    return f"[{ENV_LABEL.title()}] " if ENV_LABEL else ""
