"""
Django settings for ATProject project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

import environ
from django.utils.csp import CSP

env = environ.Env(
    # set casting, default value
    DEBUG=(bool, False),
    # DB settings
    DB_CONN_MAX_AGE=(
        int,
        0,
    ),  # 0 = close after each request; lets Neon auto-suspend when idle
    DB_HEALTH_CHECKS=(bool, True),  # ping the DB when reusing connections (Django 4.2+)
    DB_USE_ATOMIC_REQUESTS=(
        bool,
        False,
    ),  # wrap each request in a transaction (trade-off below)
    DB_SSL_REQUIRE=(bool, True),  # force TLS if your DB supports it
    DB_CONNECT_TIMEOUT_S=(int, 5),  # fail fast on bad networks
    DB_STATEMENT_TIMEOUT_MS=(int, 15000),  # kill slow queries (15s)
    DB_IDLE_TX_TIMEOUT_MS=(int, 10000),  # kill stuck idle-in-tx sessions (10s)
    DB_LOCK_TIMEOUT_MS=(int, 2000),  # fail fast on lock waits (2s)
    DB_APP_NAME=(str, "django-app"),  # tag connections in pg_stat_activity
    DB_TARGET_SESSION_ATTRS=(
        str,
        "read-write",
    ),  # avoid accidentally hitting read-only endpoints
    DB_DISABLE_SERVER_SIDE_CURSORS=(
        bool,
        True,
    ),  # True required for Neon pooler / PgBouncer (txn pooling)
    # R2 / S3 params
    R2_ACCESS_KEY_ID=(str, ""),
    R2_SECRET_ACCESS_KEY=(str, ""),
    R2_BUCKET_NAME=(str, ""),
    R2_S3_ENDPOINT_URL=(str, ""),  # https://<ACCOUNT_ID>.r2.cloudflarestorage.com
    R2_REGION=(str, "auto"),
    R2_SIG_VERSION=(str, "s3v4"),
    R2_ADDRESSING_STYLE=(str, "path"),
    # URL behavior
    R2_SIGNED_URLS=(bool, False),  # False => public URLs; True => signed URLs
    R2_CUSTOM_DOMAIN=(
        str,
        "",
    ),  # e.g., cdn.example.com OR pub-xxxx.r2.dev (leave blank for private)
    # Caching
    R2_CACHE_CONTROL=(str, "public, max-age=31536000, immutable"),
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
environ.Env.read_env(os.path.join(BASE_DIR, ".env"))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG")

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=[])

# Railway provides RAILWAY_PUBLIC_DOMAIN for the app's domain
RAILWAY_PUBLIC_DOMAIN = env("RAILWAY_PUBLIC_DOMAIN", default=None)
if RAILWAY_PUBLIC_DOMAIN:
    ALLOWED_HOSTS.append(RAILWAY_PUBLIC_DOMAIN)

# Railway health checks use this host
ALLOWED_HOSTS.append("healthcheck.railway.app")

# CSRF trusted origins for Railway and custom domains
CSRF_TRUSTED_ORIGINS = env.list("CSRF_TRUSTED_ORIGINS", default=[])
if RAILWAY_PUBLIC_DOMAIN:
    CSRF_TRUSTED_ORIGINS.append(f"https://{RAILWAY_PUBLIC_DOMAIN}")

ADMINS = env.list("ADMINS", default=[])

# ==============================================================================
# SECURITY SETTINGS (PRODUCTION)
# ==============================================================================

if not DEBUG:
    # --- SSL / HTTPS ---
    # Trust X-Forwarded-Proto header from Cloudflare/Railway proxy
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = env.bool("DJANGO_SECURE_SSL_REDIRECT", default=True)
    SESSION_COOKIE_SECURE = env.bool("DJANGO_SESSION_COOKIE_SECURE", default=True)
    CSRF_COOKIE_SECURE = env.bool("DJANGO_CSRF_COOKIE_SECURE", default=True)

    # --- HSTS (HTTP Strict Transport Security) ---
    # Default: 1 year. Override via DJANGO_SECURE_HSTS_SECONDS env var if needed.
    SECURE_HSTS_SECONDS = env.int("DJANGO_SECURE_HSTS_SECONDS", default=31536000)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = env.bool(
        "DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS", default=True
    )
    SECURE_HSTS_PRELOAD = env.bool("DJANGO_SECURE_HSTS_PRELOAD", default=True)

    # --- Other Security Headers ---
    # Modern browsers have deprecated XSS protection in favor of strong Content
    # Security Policy (CSP), which should be configured separately.
    # SECURE_BROWSER_XSS_FILTER is True by default in Django 5 but will be removed.
    SECURE_CONTENT_TYPE_NOSNIFF = env.bool(
        "DJANGO_SECURE_CONTENT_TYPE_NOSNIFF", default=True
    )

    # --- Explicit security defaults (Django defaults are safe, but explicit is better) ---
    SESSION_COOKIE_HTTPONLY = True
    X_FRAME_OPTIONS = "DENY"
    SECURE_REFERRER_POLICY = "same-origin"
    SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin"

# ==============================================================================
# CONTENT SECURITY POLICY (Django 6.0 built-in)
# https://docs.djangoproject.com/en/6.0/ref/csp/
# ==============================================================================

# Base CSP directives (R2 domain added dynamically below)
_CSP_IMG_SRC = ["'self'", "data:"]
_CSP_MEDIA_SRC = ["'self'"]
_CSP_CONNECT_SRC = ["'self'", "https://cloudflareinsights.com"]

# CSP.NONCE is replaced with a per-request 'nonce-<value>' in the header.
# It lets nonced scripts run; 'unsafe-inline' is the fallback for older
# browsers (ignored when a nonce is present). 'self' + explicit origins cover
# Django admin scripts, MathJax (jsdelivr), and Cloudflare analytics.
# Note: 'strict-dynamic' was removed because it causes browsers to ignore the
# 'self' and URL allowlists, which blocks Django admin scripts.
_CSP_DIRECTIVES = {
    "default-src": ["'self'"],
    "script-src": [
        "'self'",
        "'unsafe-inline'",
        CSP.NONCE,
        "https://cdn.jsdelivr.net",
        "https://static.cloudflareinsights.com",
    ],
    # MathJax requires 'unsafe-inline' for dynamic styles
    "style-src": ["'self'", "'unsafe-inline'"],
    # MathJax loads fonts from jsdelivr CDN
    "font-src": ["'self'", "https://cdn.jsdelivr.net"],
    "img-src": _CSP_IMG_SRC,
    "media-src": _CSP_MEDIA_SRC,
    "connect-src": _CSP_CONNECT_SRC,
    "form-action": ["'self'"],
    "frame-ancestors": ["'self'"],
    "base-uri": ["'self'"],
}

# Enforced policy (production) or report-only (development)
if DEBUG:
    SECURE_CSP_REPORT_ONLY = _CSP_DIRECTIVES
else:
    SECURE_CSP = _CSP_DIRECTIVES


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.postgres",
    "django.contrib.sitemaps",
    "engine",
]

# THIRD-PARTY APPS
INSTALLED_APPS += [
    # Optional: enable result/beat Django apps
    "django_celery_results",
    "django_celery_beat",
    "storages",
]

# Django Debug Toolbar (dev only)
if DEBUG:
    try:
        import debug_toolbar  # noqa: F401

        INSTALLED_APPS += ["debug_toolbar"]
    except ImportError:
        pass

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.middleware.csp.ContentSecurityPolicyMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

if DEBUG and "debug_toolbar" in INSTALLED_APPS:
    MIDDLEWARE.insert(0, "debug_toolbar.middleware.DebugToolbarMiddleware")
    INTERNAL_IPS = ["127.0.0.1"]

ROOT_URLCONF = "ATProject.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django.template.context_processors.csp",
                "engine.context_processors.site_settings",
            ],
        },
    },
]


WSGI_APPLICATION = "ATProject.wsgi.application"

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# PostgreSQL Database Configuration
# Requires DATABASE_URL environment variable (Railway/Neon format)
# Example: postgresql://user:password@host:5432/dbname?sslmode=require
if not env("DATABASE_URL", default=None):
    raise environ.ImproperlyConfigured(
        "DATABASE_URL environment variable is required. "
        "Set it in Railway dashboard or .env file."
    )
DATABASES = {"default": env.db("DATABASE_URL")}

# ---- Recommended tweaks ----
db = DATABASES["default"]

# 1) Connection lifetime
# CONN_MAX_AGE=0 closes the DB connection at the end of every request/task.
# This lets Neon detect zero active connections and auto-suspend its compute.
# The Neon *pooler* endpoint handles server-side connection reuse, so the
# per-request TCP+TLS handshake is to the pooler — not cold-starting compute.
db["CONN_MAX_AGE"] = env.int("DB_CONN_MAX_AGE")  # 0 = close after each request
# Health checks only matter when connections are reused (CONN_MAX_AGE > 0).
# With CONN_MAX_AGE=0 each request gets a fresh connection, so disable the
# extra ping — it's a wasted round-trip that can wake Neon's compute.
db["CONN_HEALTH_CHECKS"] = db["CONN_MAX_AGE"] > 0

# 2) Safety/ergonomics per request
db["ATOMIC_REQUESTS"] = env.bool("DB_USE_ATOMIC_REQUESTS")  # see notes below

# 3) Neon serverless / PgBouncer compatibility
# When using Neon's pooled connection endpoint (-pooler), disable server-side cursors
db["DISABLE_SERVER_SIDE_CURSORS"] = env.bool("DB_DISABLE_SERVER_SIDE_CURSORS")

# 4) Driver / libpq options
db.setdefault("OPTIONS", {})
db["OPTIONS"].update(
    {
        # libpq keyword args (preferred where available)
        "sslmode": "require" if env.bool("DB_SSL_REQUIRE") else "prefer",
        "connect_timeout": env.int("DB_CONNECT_TIMEOUT_S"),
        "application_name": env.str("DB_APP_NAME"),
        "target_session_attrs": env.str("DB_TARGET_SESSION_ATTRS"),
    }
)

# 5) Neon-specific: Add endpoint ID for SNI routing if provided
# Only needed for DIRECT connections (not pooler URLs which have -pooler in hostname)
# Pooler URLs already include endpoint info in the hostname
NEON_ENDPOINT_ID = env("NEON_ENDPOINT_ID", default=None)
DATABASE_URL = env("DATABASE_URL", default="")
if NEON_ENDPOINT_ID and "-pooler" not in DATABASE_URL:
    db["OPTIONS"]["options"] = f"-c endpoint={NEON_ENDPOINT_ID}"


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "America/New_York"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
# For Whitenoise
STATIC_ROOT = BASE_DIR / "staticfiles"

# Only in development
if DEBUG:
    WHITENOISE_USE_FINDERS = True

# WhiteNoise (optional but recommended if static is local)
if "whitenoise.middleware.WhiteNoiseMiddleware" in MIDDLEWARE:
    STORAGES = {
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
        "default": {  # media on R2 (set below)
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        },
    }
else:
    STORAGES = {
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
        "default": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        },
    }

# ---- R2 / django-storages (media) ----
AWS_ACCESS_KEY_ID = env("R2_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = env("R2_SECRET_ACCESS_KEY")
AWS_STORAGE_BUCKET_NAME = env("R2_BUCKET_NAME")
AWS_S3_ENDPOINT_URL = env("R2_S3_ENDPOINT_URL")
AWS_S3_REGION_NAME = env("R2_REGION")
AWS_S3_SIGNATURE_VERSION = env("R2_SIG_VERSION")
AWS_S3_ADDRESSING_STYLE = env("R2_ADDRESSING_STYLE")
AWS_DEFAULT_ACL = None

# Build URL behavior from env flags
AWS_S3_CUSTOM_DOMAIN = env("R2_CUSTOM_DOMAIN") or None
AWS_QUERYSTRING_AUTH = env.bool("R2_SIGNED_URLS")

# Default to signed URLs when no public domain is configured (R2 buckets are private by default)
if AWS_S3_CUSTOM_DOMAIN is None and not AWS_QUERYSTRING_AUTH:
    AWS_QUERYSTRING_AUTH = True

# Set Cache-Control on objects
AWS_S3_OBJECT_PARAMETERS = {"CacheControl": env("R2_CACHE_CONTROL")}

# MEDIA_URL:
# - Public: use the custom domain (r2.dev or your domain)
# - Private: MEDIA_URL is a placeholder; actual URLs are signed when calling file.url
if AWS_S3_CUSTOM_DOMAIN:
    MEDIA_URL = f"https://{AWS_S3_CUSTOM_DOMAIN.rstrip('/')}/"
    # Add R2 custom domain to CSP for images and media
    _CSP_IMG_SRC.append(f"https://{AWS_S3_CUSTOM_DOMAIN}")
    _CSP_MEDIA_SRC.append(f"https://{AWS_S3_CUSTOM_DOMAIN}")
elif AWS_S3_ENDPOINT_URL:
    MEDIA_URL = f"{AWS_S3_ENDPOINT_URL.rstrip('/')}/{AWS_STORAGE_BUCKET_NAME}/"
    # Add R2 endpoint to CSP for images and media (signed URLs)
    _CSP_IMG_SRC.append(AWS_S3_ENDPOINT_URL.rstrip("/"))
    _CSP_MEDIA_SRC.append(AWS_S3_ENDPOINT_URL.rstrip("/"))
else:
    MEDIA_URL = f"https://{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com/"

# Add R2 endpoint to connect-src for presigned uploads (always uses raw endpoint, not custom domain)
if AWS_S3_ENDPOINT_URL:
    _CSP_CONNECT_SRC.append(AWS_S3_ENDPOINT_URL.rstrip("/"))

# # Dev ergonomics: keep media local if you prefer
# if DEBUG and env.bool("USE_LOCAL_MEDIA_IN_DEV", default=False):
#     STORAGES["default"] = {"BACKEND": "django.core.files.storage.FileSystemStorage"}
#     MEDIA_URL = "/media/"
#     MEDIA_ROOT = BASE_DIR / "media"

# # Media files (User uploads)
# MEDIA_URL = "/media/"
# MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Celery (Redis)
CELERY_BROKER_URL = env("REDIS_URL", default="memory://")

# Result backend — MUST be Redis (not "django-db") to allow Neon auto-suspend.
# Using "django-db" writes to the database after every task, keeping Neon awake.
_celery_result_backend = env("CELERY_RESULT_BACKEND", default=CELERY_BROKER_URL)
if _celery_result_backend == "django-db":
    import warnings

    warnings.warn(
        "CELERY_RESULT_BACKEND='django-db' prevents Neon from scaling to zero. "
        "Falling back to Redis. Remove the env var or set it to your REDIS_URL.",
        stacklevel=1,
    )
    _celery_result_backend = CELERY_BROKER_URL
CELERY_RESULT_BACKEND = _celery_result_backend

# Beat scheduler — file-based to avoid DB polling.
# DatabaseScheduler polls the DB every 5 seconds (~17K queries/day).
CELERY_BEAT_SCHEDULER = "celery.beat:PersistentScheduler"
CELERY_BEAT_SCHEDULE_FILENAME = "/tmp/celerybeat-schedule"
CELERY_BEAT_SCHEDULE = {
    "publish-scheduled-posts": {
        "task": "engine.tasks.publish_scheduled_posts",
        "schedule": 60.0,  # every 60 seconds
    },
}


# ==============================================================================
# ASSET PIPELINE
# ==============================================================================
# Widths generated for responsive images. Widths >= original are skipped.
# Override via env as comma-separated list, e.g. "480,960,1440".
_rendition_widths_env = env("ASSET_RENDITION_WIDTHS", default="")
ASSET_RENDITION_WIDTHS = (
    [int(w.strip()) for w in _rendition_widths_env.split(",") if w.strip()]
    if _rendition_widths_env
    else [400, 800, 1200, 1600]
)
# JPEG quality (1-95). Higher = larger files, better quality.
ASSET_RENDITION_JPEG_QUALITY = env.int("ASSET_RENDITION_JPEG_QUALITY", default=85)


# Recommended dev defaults
CELERY_TASK_ALWAYS_EAGER = False  # set True in unit tests
CELERY_TASK_EAGER_PROPAGATES = False
CELERY_TASK_TIME_LIMIT = 60 * 5  # hard limit, seconds
CELERY_TASK_SOFT_TIME_LIMIT = 60 * 4
CELERY_TASK_SERIALIZER = "json"
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_RESULT_EXPIRES = 60 * 60  # 1 hour
CELERY_ENABLE_UTC = True  # Celery reads Django's TZ too


# ==============================================================================
# CACHING (Redis)
# ==============================================================================
# Use Redis for caching (same instance as Celery broker)
REDIS_URL = env("REDIS_URL", default=None)
if REDIS_URL:
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": REDIS_URL,
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
            },
            "KEY_PREFIX": "architextual",
        }
    }
    # Use Redis-backed sessions with database fallback for persistence.
    # If Redis goes down, sessions are still recoverable from the database.
    SESSION_ENGINE = "django.contrib.sessions.backends.cached_db"
    SESSION_CACHE_ALIAS = "default"
else:
    # Fallback to local memory cache for development without Redis
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "unique-snowflake",
        }
    }
    # Explicitly use cache-backed sessions even without Redis, so Django
    # never falls back to its default database-backed session engine.
    SESSION_ENGINE = "django.contrib.sessions.backends.cache"
    SESSION_CACHE_ALIAS = "default"


# ==============================================================================
# DJANGO ADMIN CONFIGURATION
# ==============================================================================

# Customize admin site header and title
ADMIN_URL = env("ADMIN_URL", default="manage/")
ADMIN_SITE_HEADER = "Architextual Admin"
ADMIN_SITE_TITLE = "Architextual"
ADMIN_INDEX_TITLE = "Site Administration"


# ==============================================================================
# PRESIGNED UPLOAD CONFIGURATION
# ==============================================================================

# Expiry time for presigned upload URLs (in seconds)
PRESIGNED_UPLOAD_EXPIRY_SECONDS = env.int("PRESIGNED_UPLOAD_EXPIRY", default=3600)

# API token for programmatic access to presigned upload endpoints
# If not set, only session-based authentication will work
PRESIGNED_UPLOAD_API_TOKEN = env("PRESIGNED_UPLOAD_API_TOKEN", default=None)

# Maximum file sizes per asset type (for direct presigned uploads)
# These are larger than proxy limits since files go directly to R2
ASSET_MAX_SIZES = {
    "image": 1 * 1024 * 1024 * 1024,  # 1GB (large RAW/TIFF files)
    "video": 5 * 1024 * 1024 * 1024,  # 5GB
    "audio": 500 * 1024 * 1024,  # 500MB
    "document": 500 * 1024 * 1024,  # 500MB
    "archive": 2 * 1024 * 1024 * 1024,  # 2GB
    "other": 500 * 1024 * 1024,  # 500MB
}


# ==============================================================================
# LOGGING
# ==============================================================================

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "[{asctime}] {levelname} {name} {message}",
            "style": "{",
        },
        "json": {
            "()": "django.utils.log.ServerFormatter",
            "format": "[{asctime}] {levelname} {name} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose" if DEBUG else "json",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "WARNING",
    },
    "loggers": {
        "django.request": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
        },
        "engine": {
            "handlers": ["console"],
            "level": "INFO" if DEBUG else "WARNING",
            "propagate": False,
        },
        "celery": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}


# ==============================================================================
# SENTRY (Error Tracking)
# ==============================================================================

SENTRY_DSN = env("SENTRY_DSN", default=None)
if SENTRY_DSN:
    try:
        import sentry_sdk

        sentry_sdk.init(
            dsn=SENTRY_DSN,
            traces_sample_rate=0.1,
            profiles_sample_rate=0.1,
            send_default_pii=False,
            environment=env("SENTRY_ENVIRONMENT", default="production"),
        )
    except ImportError:
        pass
