# Generated by Django 5.2.7 on 2025-10-06 15:11

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Series",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("title", models.CharField(max_length=200, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name_plural": "series",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("name", models.CharField(max_length=64, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=80, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("name", models.CharField(max_length=64, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=80, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="engine.category",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("title", models.CharField(max_length=200)),
                ("subtitle", models.CharField(blank=True, max_length=240)),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="Auto-generated from title if blank.",
                        max_length=220,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Optional summary/teaser."),
                ),
                (
                    "show_toc",
                    models.BooleanField(
                        default=False, help_text="Optionally show table of contents."
                    ),
                ),
                (
                    "content_markdown",
                    models.TextField(help_text="Author in markdown only."),
                ),
                (
                    "content_html_cached",
                    models.TextField(
                        blank=True,
                        help_text="Optional cache of rendered+processed HTML.",
                    ),
                ),
                ("word_count", models.PositiveIntegerField(default=0)),
                (
                    "reading_time_minutes",
                    models.PositiveSmallIntegerField(
                        default=1, help_text="Approximate reading time."
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        default="en",
                        help_text="IETF tag, e.g., 'en', 'zh-TW'.",
                        max_length=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("scheduled", "Scheduled"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=12,
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("unlisted", "Unlisted"),
                            ("private", "Private"),
                        ],
                        db_index=True,
                        default="public",
                        max_length=12,
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, db_index=True, help_text="Go-live time.", null=True
                    ),
                ),
                (
                    "expire_at",
                    models.DateTimeField(
                        blank=True, help_text="Optional unpublish time.", null=True
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("is_pinned", models.BooleanField(default=False)),
                ("pin_order", models.IntegerField(default=0)),
                ("allow_comments", models.BooleanField(default=True)),
                ("comment_count", models.PositiveIntegerField(default=0)),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("like_count", models.PositiveIntegerField(default=0)),
                (
                    "rating",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                (
                    "certainty",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "1"),
                            (2, "2"),
                            (3, "3"),
                            (4, "4"),
                            (5, "5"),
                            (6, "6"),
                            (7, "7"),
                            (8, "8"),
                            (9, "9"),
                            (10, "10"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "importance",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "1"),
                            (2, "2"),
                            (3, "3"),
                            (4, "4"),
                            (5, "5"),
                            (6, "6"),
                            (7, "7"),
                            (8, "8"),
                            (9, "9"),
                            (10, "10"),
                        ],
                        default=1,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("extras", models.JSONField(blank=True, null=True)),
                ("table_of_contents", models.JSONField(blank=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True, related_name="posts", to="engine.category"
                    ),
                ),
                (
                    "co_authors",
                    models.ManyToManyField(
                        blank=True,
                        related_name="posts_coauthored",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "last_edited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posts_edited",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posts_published",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_posts",
                    models.ManyToManyField(
                        blank=True, related_name="related_to", to="engine.post"
                    ),
                ),
                (
                    "series",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posts",
                        to="engine.series",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="posts", to="engine.tag"
                    ),
                ),
            ],
            options={
                "ordering": ["-is_pinned", "pin_order", "-published_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "key",
                    models.SlugField(
                        blank=True,
                        help_text="Global unique key for markdown reference. Leave blank for auto-generation with smart prefixes. Use in markdown as @asset:key",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Human-readable title", max_length=255),
                ),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("video", "Video"),
                            ("audio", "Audio"),
                            ("document", "Document"),
                            ("archive", "Archive"),
                            ("other", "Other"),
                        ],
                        help_text="Type of asset (auto-detected from file extension)",
                        max_length=20,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="The asset file (max: 100MB for images, 500MB for videos)",
                        upload_to="assets/%Y/%m/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "gif",
                                    "webp",
                                    "svg",
                                    "bmp",
                                    "ico",
                                    "mp4",
                                    "webm",
                                    "mov",
                                    "avi",
                                    "mkv",
                                    "m4v",
                                    "mp3",
                                    "wav",
                                    "ogg",
                                    "m4a",
                                    "flac",
                                    "aac",
                                    "pdf",
                                    "epub",
                                    "doc",
                                    "docx",
                                    "txt",
                                    "md",
                                    "csv",
                                    "json",
                                    "xml",
                                    "jsonl",
                                    "tsv",
                                    "yaml",
                                    "yml",
                                ]
                            )
                        ],
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(
                        blank=True,
                        help_text="Original filename when uploaded",
                        max_length=255,
                    ),
                ),
                (
                    "file_extension",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="File extension (e.g., 'jpg', 'mp4')",
                        max_length=20,
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Alternative text for accessibility (required for images)",
                        max_length=255,
                    ),
                ),
                (
                    "caption",
                    models.TextField(
                        blank=True, help_text="Caption to display with asset"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Detailed description for admin/search"
                    ),
                ),
                (
                    "credit",
                    models.CharField(
                        blank=True,
                        help_text="Credit/attribution (e.g., 'Photo by John Doe')",
                        max_length=255,
                    ),
                ),
                (
                    "license",
                    models.CharField(
                        blank=True,
                        help_text="License information (e.g., 'CC BY 4.0')",
                        max_length=100,
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        blank=True, help_text="File size in bytes", null=True
                    ),
                ),
                (
                    "mime_type",
                    models.CharField(
                        blank=True,
                        help_text="MIME type (e.g., 'image/jpeg')",
                        max_length=100,
                    ),
                ),
                (
                    "width",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Width in pixels (for images/videos)",
                        null=True,
                    ),
                ),
                (
                    "height",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Height in pixels (for images/videos)",
                        null=True,
                    ),
                ),
                (
                    "duration",
                    models.DurationField(
                        blank=True, help_text="Duration (for audio/video)", null=True
                    ),
                ),
                (
                    "bitrate",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Bitrate in kbps (for audio/video)",
                        null=True,
                    ),
                ),
                (
                    "frame_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Frame rate in fps (for video)",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "file_hash",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="SHA256 hash for deduplication",
                        max_length=64,
                    ),
                ),
                (
                    "collection",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Group assets into collections (e.g., 'blog-2024', 'diagrams')",
                        max_length=100,
                    ),
                ),
                (
                    "folder",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Virtual folder path for organizing assets (e.g., 'images/photos/2024')",
                        max_length=255,
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this asset is publicly accessible",
                    ),
                ),
                (
                    "permissions",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Custom permissions for this asset (e.g., user/group access)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("ready", "Ready for Use"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="ready",
                        help_text="Asset status workflow",
                        max_length=20,
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        blank=True,
                        help_text="Original source URL if asset was imported",
                    ),
                ),
                (
                    "focal_point_x",
                    models.FloatField(
                        blank=True,
                        help_text="X coordinate (0.0-1.0) for image focal point",
                        null=True,
                    ),
                ),
                (
                    "focal_point_y",
                    models.FloatField(
                        blank=True,
                        help_text="Y coordinate (0.0-1.0) for image focal point",
                        null=True,
                    ),
                ),
                (
                    "usage_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of posts using this asset"
                    ),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of times this asset has been viewed",
                    ),
                ),
                (
                    "download_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of times this asset has been downloaded",
                    ),
                ),
                (
                    "last_accessed",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time this asset was accessed/viewed",
                        null=True,
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who uploaded this asset",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_assets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Tags for organizing assets",
                        related_name="assets",
                        to="engine.tag",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AssetMetadata",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "asset",
                    models.OneToOneField(
                        help_text="Asset this metadata belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="metadata",
                        serialize=False,
                        to="engine.asset",
                    ),
                ),
                (
                    "exif_data",
                    models.JSONField(
                        blank=True, help_text="Raw EXIF data from image", null=True
                    ),
                ),
                (
                    "camera_make",
                    models.CharField(
                        blank=True,
                        help_text="Camera manufacturer (e.g., 'Canon', 'Nikon')",
                        max_length=100,
                    ),
                ),
                (
                    "camera_model",
                    models.CharField(
                        blank=True,
                        help_text="Camera model (e.g., 'EOS 5D Mark IV')",
                        max_length=100,
                    ),
                ),
                (
                    "lens",
                    models.CharField(
                        blank=True,
                        help_text="Lens used (e.g., 'EF 24-70mm f/2.8L II USM')",
                        max_length=100,
                    ),
                ),
                (
                    "focal_length",
                    models.FloatField(
                        blank=True, help_text="Focal length in mm", null=True
                    ),
                ),
                (
                    "aperture",
                    models.FloatField(
                        blank=True,
                        help_text="Aperture f-stop (e.g., 2.8, 5.6)",
                        null=True,
                    ),
                ),
                (
                    "shutter_speed",
                    models.CharField(
                        blank=True,
                        help_text="Shutter speed (e.g., '1/500', '2s')",
                        max_length=50,
                    ),
                ),
                (
                    "iso",
                    models.IntegerField(
                        blank=True, help_text="ISO sensitivity", null=True
                    ),
                ),
                (
                    "captured_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time the photo/video was captured",
                        null=True,
                    ),
                ),
                (
                    "latitude",
                    models.FloatField(blank=True, help_text="GPS latitude", null=True),
                ),
                (
                    "longitude",
                    models.FloatField(blank=True, help_text="GPS longitude", null=True),
                ),
                (
                    "location_name",
                    models.CharField(
                        blank=True,
                        help_text="Human-readable location name",
                        max_length=255,
                    ),
                ),
                (
                    "artist",
                    models.CharField(
                        blank=True,
                        help_text="Artist/performer name (audio)",
                        max_length=255,
                    ),
                ),
                (
                    "album",
                    models.CharField(
                        blank=True, help_text="Album name (audio)", max_length=255
                    ),
                ),
                (
                    "genre",
                    models.CharField(
                        blank=True, help_text="Genre (audio)", max_length=100
                    ),
                ),
                (
                    "year",
                    models.IntegerField(
                        blank=True, help_text="Year of creation/publication", null=True
                    ),
                ),
                (
                    "track_number",
                    models.IntegerField(
                        blank=True, help_text="Track number in album (audio)", null=True
                    ),
                ),
                (
                    "author",
                    models.CharField(
                        blank=True,
                        help_text="Author/creator name (documents)",
                        max_length=255,
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True,
                        help_text="Subject/topic (documents)",
                        max_length=255,
                    ),
                ),
                (
                    "keywords",
                    models.TextField(
                        blank=True, help_text="Keywords/tags from document metadata"
                    ),
                ),
                (
                    "page_count",
                    models.IntegerField(
                        blank=True, help_text="Number of pages (documents)", null=True
                    ),
                ),
                (
                    "dominant_colors",
                    models.JSONField(
                        blank=True,
                        help_text="Dominant colors in the image (array of hex codes)",
                        null=True,
                    ),
                ),
                (
                    "color_palette",
                    models.JSONField(
                        blank=True,
                        help_text="Color palette extracted from image",
                        null=True,
                    ),
                ),
                (
                    "average_color",
                    models.CharField(
                        blank=True,
                        help_text="Average color as hex code (e.g., '#FF5733')",
                        max_length=7,
                    ),
                ),
                (
                    "color_space",
                    models.CharField(
                        blank=True,
                        help_text="Color space (e.g., 'sRGB', 'Adobe RGB', 'ProPhoto RGB')",
                        max_length=50,
                    ),
                ),
                (
                    "color_profile",
                    models.CharField(
                        blank=True, help_text="ICC color profile name", max_length=100
                    ),
                ),
                (
                    "dpi",
                    models.IntegerField(
                        blank=True,
                        help_text="Dots per inch (DPI) for images",
                        null=True,
                    ),
                ),
                (
                    "has_alpha",
                    models.BooleanField(
                        default=False,
                        help_text="Whether image has alpha channel (transparency)",
                    ),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional custom metadata fields",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Asset Metadata",
                "verbose_name_plural": "Asset Metadata",
                "indexes": [
                    models.Index(
                        fields=["camera_make", "camera_model"],
                        name="engine_asse_camera__d839ac_idx",
                    ),
                    models.Index(
                        fields=["captured_at"], name="engine_asse_capture_451a28_idx"
                    ),
                    models.Index(
                        fields=["artist", "album"], name="engine_asse_artist_f63509_idx"
                    ),
                    models.Index(
                        fields=["author"], name="engine_asse_author_0958cc_idx"
                    ),
                    models.Index(fields=["year"], name="engine_asse_year_f57b9c_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="AssetRendition",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this rendition",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "width",
                    models.PositiveIntegerField(help_text="Width of this rendition"),
                ),
                (
                    "height",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Height of this rendition (may be auto-calculated)",
                        null=True,
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        default="auto",
                        help_text="Image format (jpeg, webp, auto)",
                        max_length=10,
                    ),
                ),
                (
                    "quality",
                    models.CharField(
                        choices=[
                            ("low", "Low (60%)"),
                            ("medium", "Medium (75%)"),
                            ("high", "High (85%)"),
                            ("max", "Maximum (95%)"),
                        ],
                        default="high",
                        help_text="Compression quality",
                        max_length=10,
                    ),
                ),
                (
                    "preset",
                    models.CharField(
                        blank=True,
                        help_text="Preset/size name (e.g., 'thumbnail', 'hero', 'card', 'small', 'medium', 'large')",
                        max_length=50,
                    ),
                ),
                (
                    "file",
                    models.ImageField(
                        help_text="Rendition file", upload_to="assets/renditions/%Y/%m/"
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(help_text="File size in bytes"),
                ),
                (
                    "bitrate",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Bitrate in kbps (for video/audio renditions)",
                        null=True,
                    ),
                ),
                (
                    "codec",
                    models.CharField(
                        blank=True,
                        help_text="Codec used for encoding (e.g., 'h264', 'vp9', 'aac')",
                        max_length=50,
                    ),
                ),
                (
                    "cdn_url",
                    models.URLField(
                        blank=True,
                        help_text="CDN URL for this rendition (if using external CDN)",
                        max_length=500,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="completed",
                        help_text="Generation status",
                        max_length=20,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if generation failed"
                    ),
                ),
                (
                    "is_webp",
                    models.BooleanField(
                        default=False, help_text="Is this a WebP rendition"
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="renditions",
                        to="engine.asset",
                    ),
                ),
            ],
            options={
                "ordering": ["width"],
                "indexes": [
                    models.Index(
                        fields=["asset", "width", "format"],
                        name="engine_asse_asset_i_5c2c07_idx",
                    ),
                    models.Index(
                        fields=["status"], name="engine_asse_status_08eb8d_idx"
                    ),
                    models.Index(
                        fields=["preset", "asset"], name="engine_asse_preset_35bf10_idx"
                    ),
                    models.Index(
                        fields=["codec", "format"], name="engine_asse_codec_cec133_idx"
                    ),
                ],
                "unique_together": {("asset", "width", "format", "quality")},
            },
        ),
        migrations.CreateModel(
            name="PostAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "alias",
                    models.SlugField(
                        blank=True,
                        help_text="Optional short alias for this post (e.g., 'diagram1' → 'diagram-2024-revenue'). Use in markdown as @alias",
                        max_length=100,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Display order in admin"
                    ),
                ),
                (
                    "custom_caption",
                    models.TextField(
                        blank=True, help_text="Override default caption for this post"
                    ),
                ),
                (
                    "custom_alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Override default alt text for this post",
                        max_length=255,
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_usages",
                        to="engine.asset",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_assets",
                        to="engine.post",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["post", "order"], name="engine_post_post_id_40c24f_idx"
                    ),
                    models.Index(
                        fields=["post", "asset"], name="engine_post_post_id_d82442_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("alias", ""), _negated=True),
                        fields=("post", "alias"),
                        name="unique_post_alias_when_not_blank",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["status", "published_at"], name="engine_post_status_57c47c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["visibility", "published_at"],
                name="engine_post_visibil_9c43d4_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="post",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["draft", "archived"]),
                    ("published_at__isnull", False),
                    _connector="OR",
                ),
                name="published_or_scheduled_requires_published_at",
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(fields=["key"], name="engine_asse_key_c3c23a_idx"),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["asset_type", "-created_at"],
                name="engine_asse_asset_t_ca9002_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["is_deleted", "asset_type"],
                name="engine_asse_is_dele_fa0a19_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["file_hash"], name="engine_asse_file_ha_879da1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["collection", "-created_at"],
                name="engine_asse_collect_90df62_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["status", "-created_at"], name="engine_asse_status_178447_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["uploaded_by", "-created_at"],
                name="engine_asse_uploade_0cf03b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["file_extension", "asset_type"],
                name="engine_asse_file_ex_8a9701_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["folder", "-created_at"], name="engine_asse_folder_a5bc0b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["is_public", "status"], name="engine_asse_is_publ_c4ff7f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["-last_accessed"], name="engine_asse_last_ac_52340f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["-view_count"], name="engine_asse_view_co_4dd530_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["-download_count"], name="engine_asse_downloa_b00933_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="asset",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("file_size__gte", 0), ("file_size__isnull", True), _connector="OR"
                ),
                name="asset_file_size_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="asset",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("width__gte", 0), ("width__isnull", True), _connector="OR"
                ),
                name="asset_width_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="asset",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("height__gte", 0), ("height__isnull", True), _connector="OR"
                ),
                name="asset_height_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="asset",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("focal_point_x__gte", 0.0), ("focal_point_x__lte", 1.0)),
                    ("focal_point_x__isnull", True),
                    _connector="OR",
                ),
                name="asset_focal_point_x_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="asset",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("focal_point_y__gte", 0.0), ("focal_point_y__lte", 1.0)),
                    ("focal_point_y__isnull", True),
                    _connector="OR",
                ),
                name="asset_focal_point_y_range",
            ),
        ),
    ]
