# Generated by Django 5.2.7 on 2025-10-06 18:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Tag name", max_length=50, unique=True),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly tag identifier", unique=True
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#3B82F6",
                        help_text="Hex color for visual distinction (e.g., #3B82F6)",
                        max_length=7,
                    ),
                ),
            ],
            options={
                "verbose_name": "Asset Tag",
                "verbose_name_plural": "Asset Tags",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AssetCollection",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(help_text="Collection name", max_length=255)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Collection description"),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this collection is publicly visible",
                    ),
                ),
                (
                    "assets",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Assets in this collection",
                        related_name="collections",
                        to="engine.asset",
                    ),
                ),
                (
                    "cover_asset",
                    models.ForeignKey(
                        blank=True,
                        help_text="Cover image for this collection",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="engine.asset",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Collection owner",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asset_collections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Asset Collection",
                "verbose_name_plural": "Asset Collections",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AssetFolder",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(help_text="Folder name", max_length=255)),
                (
                    "path",
                    models.CharField(
                        editable=False, help_text="Computed full path", max_length=1000
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent folder (null for root folders)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="engine.assetfolder",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Folder owner",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asset_folders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Asset Folder",
                "verbose_name_plural": "Asset Folders",
                "ordering": ["path"],
                "unique_together": {("user", "parent", "name")},
            },
        ),
        migrations.AddField(
            model_name="asset",
            name="asset_folder",
            field=models.ForeignKey(
                blank=True,
                help_text="Folder this asset belongs to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="folder_assets",
                to="engine.assetfolder",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="asset_tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="Asset-specific tags (separate from post tags)",
                related_name="tagged_assets",
                to="engine.assettag",
            ),
        ),
    ]
