# Generated by Django 5.2.7 on 2025-10-06 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0002_assettag_assetcollection_assetfolder_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="asset",
            name="engine_asse_collect_90df62_idx",
        ),
        migrations.RemoveIndex(
            model_name="asset",
            name="engine_asse_folder_a5bc0b_idx",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="collection",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="folder",
        ),
    ]
