# Generated by Django 5.2.7 on 2025-10-06 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0003_remove_asset_engine_asse_collect_90df62_idx_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="asset",
            name="tags",
        ),
    ]
