# Generated by Django 5.2.7 on 2025-10-07 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0004_remove_asset_tags"),
    ]

    operations = [
        migrations.CreateModel(
            name="InternalLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "link_text",
                    models.CharField(
                        blank=True,
                        help_text="The anchor text of the link",
                        max_length=500,
                    ),
                ),
                (
                    "link_context",
                    models.TextField(
                        blank=True, help_text="Surrounding text for context (optional)"
                    ),
                ),
                (
                    "source_post",
                    models.ForeignKey(
                        help_text="The post that contains the link",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_links",
                        to="engine.post",
                    ),
                ),
                (
                    "target_post",
                    models.ForeignKey(
                        help_text="The post being linked to (these are the backlinks)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_links",
                        to="engine.post",
                    ),
                ),
            ],
            options={
                "verbose_name": "Internal Link",
                "verbose_name_plural": "Internal Links",
                "indexes": [
                    models.Index(
                        fields=["source_post"], name="engine_inte_source__47d2b8_idx"
                    ),
                    models.Index(
                        fields=["target_post"], name="engine_inte_target__0b5e73_idx"
                    ),
                    models.Index(
                        fields=["is_deleted", "source_post"],
                        name="engine_inte_is_dele_e4d16a_idx",
                    ),
                    models.Index(
                        fields=["is_deleted", "target_post"],
                        name="engine_inte_is_dele_e41390_idx",
                    ),
                ],
                "unique_together": {("source_post", "target_post")},
            },
        ),
    ]
