# Generated by Django 5.2.7 on 2025-10-07 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0005_add_internal_link_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="internallink",
            name="link_section_anchor",
            field=models.CharField(
                blank=True,
                help_text="Anchor ID for the section where this link appears",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="internallink",
            name="link_section_title",
            field=models.CharField(
                blank=True,
                help_text="Title of the section/header where this link appears",
                max_length=500,
            ),
        ),
    ]
