# Generated by Django 5.2.7 on 2025-10-07 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0006_add_section_context_to_internal_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="internallink",
            name="link_context",
        ),
        migrations.RemoveField(
            model_name="internallink",
            name="link_section_anchor",
        ),
        migrations.RemoveField(
            model_name="internallink",
            name="link_section_title",
        ),
        migrations.RemoveField(
            model_name="internallink",
            name="link_text",
        ),
        migrations.AddField(
            model_name="internallink",
            name="link_count",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Number of times this post links to the target (if multiple links exist)",
            ),
        ),
    ]
