# Generated by Django 5.2.7 on 2025-10-08 16:13

from django.conf import settings
from django.db import migrations, models


def populate_completion_status(apps, schema_editor):
    Post = apps.get_model("engine", "Post")
    Post.objects.filter(status="published").update(completion_status="finished")
    Post.objects.filter(status="scheduled").update(completion_status="in_progress")
    Post.objects.filter(status="draft").update(completion_status="draft")
    Post.objects.filter(status="archived").update(completion_status="abandoned")


def reset_completion_status(apps, schema_editor):
    Post = apps.get_model("engine", "Post")
    Post.objects.all().update(completion_status="draft")


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0007_simplify_internal_link_model"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE engine_post "
                        "ADD COLUMN IF NOT EXISTS abstract TEXT"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                )
            ],
            state_operations=[
                migrations.AddField(
                    model_name="post",
                    name="abstract",
                    field=models.TextField(
                        blank=True,
                        help_text="Optional article abstract in markdown (longer-form description, similar to journal article abstract).",
                    ),
                )
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE engine_post "
                        "ADD COLUMN IF NOT EXISTS completion_status VARCHAR(20) "
                        "NOT NULL DEFAULT 'draft'"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE engine_post "
                        "ALTER COLUMN completion_status DROP DEFAULT"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="post",
                    name="completion_status",
                    field=models.CharField(
                        choices=[
                            ("finished", "Finished"),
                            ("abandoned", "Abandoned"),
                            ("notes", "Notes"),
                            ("draft", "Draft"),
                            ("in_progress", "In Progress"),
                        ],
                        db_index=True,
                        default="draft",
                        help_text="Editorial completion state shown in page metadata.",
                        max_length=20,
                    ),
                )
            ],
        ),
        migrations.RunPython(
            populate_completion_status, reset_completion_status
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["completion_status"], name="engine_post_complet_a3d6e6_idx"
            ),
        ),
    ]
