# Generated by Django 5.2.7 on 2025-10-09 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0008_post_abstract_post_completion_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="first_line_caps",
            field=models.BooleanField(
                default=False,
                help_text="Style the opening paragraph with drop-cap treatment.",
                verbose_name="Intro paragraph caps",
            ),
        ),
    ]
