# Generated by Django 5.2.7 on 2025-10-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0009_post_first_line_caps"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="first_line_caps",
            field=models.BooleanField(
                default=False,
                help_text="Style the first line of opening paragraph with small caps.",
                verbose_name="Intro Paragraph Small Caps",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="show_toc",
            field=models.BooleanField(
                default=False,
                help_text="Optionally show table of contents.",
                verbose_name="Show Table of Contents",
            ),
        ),
    ]
