# Generated by Django 5.2.7 on 2025-10-10 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0010_alter_post_first_line_caps_alter_post_show_toc"),
    ]

    operations = [
        migrations.CreateModel(
            name="TagAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "alias",
                    models.CharField(
                        help_text="Alternative name for the tag (case-insensitive)",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="URL-friendly identifier for the alias",
                        max_length=80,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tag Alias",
                "verbose_name_plural": "Tag Aliases",
                "ordering": ["alias"],
            },
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={"ordering": ["-rank", "namespace", "name"]},
        ),
        migrations.AddField(
            model_name="tag",
            name="color",
            field=models.CharField(
                default="#6B7280",
                help_text="Hex color for visual distinction (e.g., #3B82F6)",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="description",
            field=models.TextField(
                blank=True, help_text="Detailed description of what this tag represents"
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="icon",
            field=models.CharField(
                blank=True,
                help_text="Icon identifier (e.g., Material icon name, emoji, or font-awesome class)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="is_active",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Whether this tag is active and available for use",
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="namespace",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Optional namespace for grouping (e.g., 'tech', 'location', 'topic')",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent tag for hierarchical organization",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="engine.tag",
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="rank",
            field=models.IntegerField(
                db_index=True,
                default=0,
                help_text="Priority/weight for sorting (higher = more important). Use for featured tags.",
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="usage_count",
            field=models.PositiveIntegerField(
                db_index=True,
                default=0,
                help_text="Number of times this tag has been used (cached)",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(
                help_text="Tag name (case-insensitive, normalized on save)",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="URL-friendly identifier",
                max_length=80,
                unique=True,
            ),
        ),
        migrations.AddIndex(
            model_name="tag",
            index=models.Index(fields=["name"], name="engine_tag_name_6b677d_idx"),
        ),
        migrations.AddIndex(
            model_name="tag",
            index=models.Index(
                fields=["namespace", "name"], name="engine_tag_namespa_2aa838_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tag",
            index=models.Index(
                fields=["parent", "name"], name="engine_tag_parent__620701_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tag",
            index=models.Index(
                fields=["is_active", "-usage_count"],
                name="engine_tag_is_acti_c33248_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="tag",
            index=models.Index(
                fields=["-rank", "name"], name="engine_tag_rank_048d23_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="tag",
            constraint=models.UniqueConstraint(
                fields=("namespace", "name"), name="unique_tag_namespace_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="tag",
            constraint=models.CheckConstraint(
                condition=models.Q(("parent", models.F("id")), _negated=True),
                name="tag_no_self_parent",
            ),
        ),
        migrations.AddField(
            model_name="tagalias",
            name="tag",
            field=models.ForeignKey(
                help_text="The canonical tag this alias points to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="aliases",
                to="engine.tag",
            ),
        ),
        migrations.AddIndex(
            model_name="tagalias",
            index=models.Index(fields=["alias"], name="engine_taga_alias_2cc5af_idx"),
        ),
        migrations.AddIndex(
            model_name="tagalias",
            index=models.Index(
                fields=["tag", "alias"], name="engine_taga_tag_id_5c1353_idx"
            ),
        ),
    ]
