# Generated by Django 5.2.9 on 2025-12-15 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0011_enhanced_tag_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly identifier for this page (e.g., 'home-intro')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Optional title for the page",
                        max_length=200,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True, help_text="Markdown content for this page"
                    ),
                ),
                (
                    "content_html",
                    models.TextField(
                        blank=True,
                        editable=False,
                        help_text="Rendered HTML (auto-generated from content)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this page content is active"
                    ),
                ),
            ],
            options={
                "verbose_name": "Page",
                "verbose_name_plural": "Pages",
                "ordering": ["slug"],
            },
        ),
    ]
