# Generated by Django 5.2.9 on 2025-12-15 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0012_page_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageFeaturedTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_title",
                    models.CharField(
                        blank=True,
                        help_text="Custom title for this section (defaults to tag name)",
                        max_length=100,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Display order (lower numbers appear first)",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="engine.page"
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="engine.tag"
                    ),
                ),
            ],
            options={
                "verbose_name": "Featured Tag",
                "verbose_name_plural": "Featured Tags",
                "ordering": ["order"],
                "unique_together": {("page", "tag")},
            },
        ),
        migrations.AddField(
            model_name="page",
            name="featured_tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="Tags to feature on this page (with custom titles and ordering)",
                through="engine.PageFeaturedTag",
                to="engine.tag",
            ),
        ),
    ]
