# Generated by Django 5.2.9 on 2025-12-16 18:33

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0013_page_featured_tags"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(
                blank=True,
                help_text="Populated automatically for full-text search. Combines title, subtitle, description, abstract, and content.",
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="post_search_vector_gin"
            ),
        ),
    ]
