# Generated by Django 5.2.9 on 2026-01-28 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0014_add_search_vector_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='upload_expires_at',
            field=models.DateTimeField(blank=True, help_text='Expiry time for presigned upload URL', null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='upload_token',
            field=models.CharField(blank=True, db_index=True, help_text='Single-use token for presigned upload verification', max_length=64, null=True, unique=True),
        ),
    ]
