# Generated by Django 5.2.9 on 2026-02-07 15:27

from django.db import migrations


def create_site_settings(apps, schema_editor):
    SiteSettings = apps.get_model("engine", "SiteSettings")
    SiteSettings.objects.get_or_create(pk=1)


def remove_site_settings(apps, schema_editor):
    SiteSettings = apps.get_model("engine", "SiteSettings")
    SiteSettings.objects.filter(pk=1).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("engine", "0016_sitesettings"),
    ]

    operations = [
        migrations.RunPython(create_site_settings, remove_site_settings),
    ]
