# Generated by Django 6.0.3 on 2026-04-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("engine", "0019_convert_unique_together_to_constraints"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="series_order",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Manual ordering within a series (lower numbers appear first).",
                null=True,
            ),
        ),
    ]
