# Generated by Django 6.0.3 on 2026-04-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("engine", "0022_add_enable_scheduled_publishing"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="canonical_url",
            field=models.URLField(
                blank=True,
                help_text="Override canonical URL for syndicated/cross-posted content.",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="hero_image_url",
            field=models.URLField(
                blank=True, help_text="Featured image URL for social sharing and cards."
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="meta_description",
            field=models.CharField(
                blank=True,
                help_text="Override meta description (falls back to description field).",
                max_length=300,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="noindex",
            field=models.BooleanField(
                default=False,
                help_text="Prevent search engines from indexing this post.",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="og_image_url",
            field=models.URLField(
                blank=True, help_text="Override Open Graph image URL."
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="default_og_image_url",
            field=models.URLField(
                blank=True,
                help_text="Default Open Graph image URL when no page-specific image exists.",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="site_description",
            field=models.CharField(
                blank=True,
                help_text="Default meta description for pages without their own.",
                max_length=300,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="site_name",
            field=models.CharField(
                default="Architextual",
                help_text="Site name used in OpenGraph tags and structured data.",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="site_url",
            field=models.URLField(
                blank=True,
                help_text="Canonical base URL, no trailing slash (e.g. https://architextual.net).",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="twitter_handle",
            field=models.CharField(
                blank=True,
                help_text="Twitter/X handle for twitter:site tag (e.g. @username).",
                max_length=50,
            ),
        ),
    ]
