# Generated by Django 6.0.3 on 2026-04-10 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0023_seo_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageFeaturedCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_title', models.CharField(blank=True, help_text='Custom title for this section (defaults to category name)', max_length=100)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.category')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.page')),
            ],
            options={
                'verbose_name': 'Featured Category',
                'verbose_name_plural': 'Featured Categories',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='page',
            name='featured_categories',
            field=models.ManyToManyField(blank=True, help_text='Categories to feature on this page (with custom titles and ordering)', through='engine.PageFeaturedCategory', to='engine.category'),
        ),
        migrations.AddConstraint(
            model_name='pagefeaturedcategory',
            constraint=models.UniqueConstraint(fields=('page', 'category'), name='unique_page_featured_category'),
        ),
    ]
