# Generated by Django 6.0.3 on 2026-04-11 16:51

import django.contrib.postgres.search
import django.core.validators
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0024_pagefeaturedcategory_page_featured_categories_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('citation_key', models.CharField(blank=True, db_index=True, help_text='Unique key for citations, e.g., "smith2024climate". Auto-generated if left blank.', max_length=120, unique=True, validators=[django.core.validators.RegexValidator(message='Citation key must start with a letter or digit, and contain only lowercase letters, digits, hyphens, and underscores.', regex=re.compile('^[a-z0-9][a-z0-9_-]*$'))])),
                ('source_type', models.CharField(choices=[('article', 'Article'), ('article-journal', 'Journal Article'), ('article-magazine', 'Magazine Article'), ('article-newspaper', 'Newspaper Article'), ('bill', 'Bill'), ('book', 'Book'), ('broadcast', 'Broadcast'), ('chapter', 'Book Chapter'), ('classic', 'Classic'), ('collection', 'Collection'), ('dataset', 'Dataset'), ('document', 'Document'), ('entry', 'Entry'), ('entry-dictionary', 'Dictionary Entry'), ('entry-encyclopedia', 'Encyclopedia Entry'), ('event', 'Event'), ('figure', 'Figure'), ('graphic', 'Graphic'), ('hearing', 'Hearing'), ('interview', 'Interview'), ('legal_case', 'Legal Case'), ('legislation', 'Legislation'), ('manuscript', 'Manuscript'), ('map', 'Map'), ('motion_picture', 'Film'), ('musical_score', 'Musical Score'), ('pamphlet', 'Pamphlet'), ('paper-conference', 'Conference Paper'), ('patent', 'Patent'), ('performance', 'Performance'), ('periodical', 'Periodical'), ('personal_communication', 'Personal Communication'), ('post', 'Post'), ('post-weblog', 'Blog Post'), ('regulation', 'Regulation'), ('report', 'Report'), ('review', 'Review'), ('review-book', 'Book Review'), ('software', 'Software'), ('song', 'Song'), ('speech', 'Speech'), ('standard', 'Standard'), ('thesis', 'Thesis'), ('treaty', 'Treaty'), ('webpage', 'Web Page')], db_index=True, default='webpage', help_text='CSL source type.', max_length=40)),
                ('title', models.TextField(help_text='Full title of the source.')),
                ('authors', models.JSONField(blank=True, default=list, help_text='List of author objects: [{"family": "Smith", "given": "John"}, ...]')),
                ('editors', models.JSONField(blank=True, default=list, help_text='List of editor objects in CSL name-variable format.')),
                ('translators', models.JSONField(blank=True, default=list, help_text='List of translator objects in CSL name-variable format.')),
                ('container_title', models.CharField(blank=True, help_text='Journal, book, or website name.', max_length=500)),
                ('publisher', models.CharField(blank=True, max_length=300)),
                ('publisher_place', models.CharField(blank=True, help_text='City of publication.', max_length=200)),
                ('volume', models.CharField(blank=True, max_length=20)),
                ('issue', models.CharField(blank=True, max_length=20)),
                ('page', models.CharField(blank=True, help_text='Page range, e.g., "100-115".', max_length=50)),
                ('edition', models.CharField(blank=True, max_length=50)),
                ('issued_date', models.JSONField(blank=True, help_text='CSL date, e.g., {"date-parts": [[2024, 3, 15]]}. Supports partial dates (year-only, year-month).', null=True)),
                ('accessed_date', models.JSONField(blank=True, help_text='Date the source was last accessed (for web sources).', null=True)),
                ('doi', models.CharField(blank=True, db_index=True, help_text='Digital Object Identifier, e.g., "10.1038/s41558-024-01234-5".', max_length=200, verbose_name='DOI')),
                ('isbn', models.CharField(blank=True, max_length=20, verbose_name='ISBN')),
                ('issn', models.CharField(blank=True, max_length=20, verbose_name='ISSN')),
                ('pmid', models.CharField(blank=True, max_length=20, verbose_name='PubMed ID')),
                ('url', models.URLField(blank=True, max_length=2000, verbose_name='URL')),
                ('abstract', models.TextField(blank=True)),
                ('language', models.CharField(blank=True, default='en', max_length=12)),
                ('note', models.TextField(blank=True, help_text='General notes about this source.')),
                ('csl_json', models.JSONField(blank=True, default=dict, help_text='Canonical CSL-JSON representation. Auto-generated from structured fields.', verbose_name='CSL-JSON')),
                ('zotero_key', models.CharField(blank=True, db_index=True, help_text='Zotero item key for sync tracking.', max_length=50)),
                ('zotero_version', models.IntegerField(blank=True, help_text='Zotero library version at last sync.', null=True)),
                ('zotero_raw', models.JSONField(blank=True, help_text='Raw Zotero JSON data.', null=True)),
                ('url_status', models.CharField(choices=[('unchecked', 'Unchecked'), ('ok', 'OK'), ('redirect', 'Redirect'), ('broken', 'Broken'), ('archived', 'Archived')], db_index=True, default='unchecked', max_length=20)),
                ('url_last_checked', models.DateTimeField(blank=True, null=True)),
                ('url_check_count', models.PositiveIntegerField(default=0)),
                ('url_archive', models.URLField(blank=True, help_text='Wayback Machine or other archive URL.', max_length=2000)),
                ('archived_file', models.FileField(blank=True, help_text='Archived copy of the source (PDF, HTML, EPUB).', upload_to='sources/%Y/%m/')),
                ('archived_file_hash', models.CharField(blank=True, help_text='SHA-256 hash for deduplication.', max_length=64)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['source_type', 'is_deleted'], name='engine_sour_source__a69f24_idx'), models.Index(fields=['url_status', 'url_last_checked'], name='engine_sour_url_sta_994c4e_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('citation_key__regex', '^[a-z0-9][a-z0-9_-]*$')), name='valid_citation_key_format')],
            },
        ),
    ]
