# Generated by Django 6.0.3 on 2026-04-11 17:44

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("engine", "0026_postcitation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="source",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(
                blank=True, null=True
            ),
        ),
    ]
