# Generated by Django 6.0.3 on 2026-04-11 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0028_sitesettings_default_citation_style_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='citation_style',
            field=models.CharField(blank=True, help_text="CSL citation style override for this post (e.g., 'chicago-author-date'). Leave blank to use the site-wide default.", max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='zotero_library_id',
            field=models.CharField(blank=True, help_text='Numeric Zotero user or group library ID (find at zotero.org/settings/keys, NOT your username).', max_length=50),
        ),
    ]
