# Generated by Django 6.0.3 on 2026-04-17 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0029_add_post_citation_style'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='postcitation',
            name='engine_post_post_id_26569a_idx',
        ),
        migrations.AddIndex(
            model_name='postcitation',
            index=models.Index(fields=['post', 'position'], name='engine_post_post_id_f38ec7_idx'),
        ),
    ]
