# Generated by Django 6.0.3 on 2026-04-20 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0030_improve_postcitation_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('uploading', 'Uploading'), ('processing', 'Processing'), ('ready', 'Ready for Use'), ('failed', 'Failed'), ('archived', 'Archived')], db_index=True, default='ready', help_text='Asset status workflow', max_length=20),
        ),
    ]
