# Generated by Django 6.0.3 on 2026-04-20 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0031_alter_asset_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetrendition',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Generation status', max_length=20),
        ),
    ]
