# Generated by Django 6.0.3 on 2026-04-20 19:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("engine", "0033_schedule_weekly_asset_cleanup"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="assetrendition",
            name="unique_asset_rendition",
        ),
        migrations.AddConstraint(
            model_name="assetrendition",
            constraint=models.UniqueConstraint(
                fields=("asset", "width", "format", "quality", "preset"),
                name="unique_asset_rendition",
            ),
        ),
    ]
