# Generated by Django 6.0.3 on 2026-04-21 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0035_add_lqip_data_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='related_posts',
        ),
        migrations.CreateModel(
            name='PostSimilarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('components', models.JSONField(blank=True, default=dict)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('source_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_outgoing', to='engine.post')),
                ('target_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_incoming', to='engine.post')),
            ],
            options={
                'verbose_name': 'Post Similarity',
                'verbose_name_plural': 'Post Similarities',
                'indexes': [models.Index(fields=['source_post', '-score'], name='postsim_source_score_idx')],
                'constraints': [models.UniqueConstraint(fields=('source_post', 'target_post'), name='unique_post_similarity')],
            },
        ),
    ]
