# Generated by Django 6.0.7 on 2026-07-18 00:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("engine", "0037_alter_assetrendition_file"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="post",
            name="engine_post_complet_a3d6e6_idx",
        ),
    ]
