# Generated by Django 6.0.7 on 2026-07-18 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("engine", "0038_remove_post_engine_post_complet_a3d6e6_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostSlugHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_slug", models.SlugField(max_length=220, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slug_history",
                        to="engine.post",
                    ),
                ),
            ],
            options={
                "verbose_name": "Post Slug History",
                "verbose_name_plural": "Post Slug History",
                "ordering": ["-created_at"],
            },
        ),
    ]
