# Generated by Django 6.0.7 on 2026-07-18 01:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("engine", "0039_postslughistory"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                condition=models.Q(
                    ("is_deleted", False),
                    ("status", "published"),
                    ("visibility", "public"),
                ),
                fields=["-published_at"],
                name="post_live_public_idx",
            ),
        ),
    ]
