# Generated by Django 6.0.7 on 2026-07-21 12:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("engine", "0040_post_post_live_public_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="source",
            name="archived_file",
            field=models.FileField(
                blank=True,
                help_text="Archived copy of the source (PDF, DOC/DOCX, or HTML).",
                upload_to="sources/%Y/%m/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "doc", "docx", "html", "htm"]
                    )
                ],
            ),
        ),
    ]
