# Generated by Django 6.0.7 on 2026-07-21 13:04

import os

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

_EXTENSION_KINDS = {
    "pdf": "pdf",
    "doc": "doc",
    "docx": "doc",
    "html": "html",
    "htm": "html",
}


def copy_archived_files(apps, schema_editor):
    """Move each Source.archived_file into a SourceFile row."""
    Source = apps.get_model("engine", "Source")
    SourceFile = apps.get_model("engine", "SourceFile")

    for source in Source.objects.exclude(archived_file="").iterator():
        name = source.archived_file.name
        ext = name.rsplit(".", 1)[-1].lower() if "." in name else ""
        SourceFile.objects.create(
            source_id=source.pk,
            file=name,
            kind=_EXTENSION_KINDS.get(ext, "other"),
            provenance="zotero" if source.zotero_key else "manual",
            sha256=source.archived_file_hash or "",
            original_filename=os.path.basename(name),
        )


def restore_archived_files(apps, schema_editor):
    """Best-effort reverse: put the first file back on Source.archived_file."""
    Source = apps.get_model("engine", "Source")
    SourceFile = apps.get_model("engine", "SourceFile")

    for sf in SourceFile.objects.order_by("source_id", "created_at").iterator():
        Source.objects.filter(pk=sf.source_id, archived_file="").update(
            archived_file=sf.file.name, archived_file_hash=sf.sha256
        )


class Migration(migrations.Migration):
    dependencies = [
        ("engine", "0041_alter_source_archived_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="SourceFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "file",
                    models.FileField(
                        help_text="Archived copy of the source (PDF, DOC/DOCX, or HTML).",
                        upload_to="sources/%Y/%m/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf", "doc", "docx", "html", "htm"]
                            )
                        ],
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pdf", "PDF"),
                            ("doc", "Word document"),
                            ("html", "HTML snapshot"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        help_text="Auto-detected from the file extension.",
                        max_length=10,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text='Optional role label, e.g. "Preprint", "Supplement".',
                        max_length=100,
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=True,
                        help_text="Show a link to this file in rendered bibliographies. Note: media storage itself is public — this only controls rendering.",
                    ),
                ),
                (
                    "provenance",
                    models.CharField(
                        choices=[
                            ("manual", "Manual upload"),
                            ("zotero", "Zotero attachment"),
                        ],
                        default="manual",
                        max_length=10,
                    ),
                ),
                (
                    "sha256",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="SHA-256 hash for deduplication.",
                        max_length=64,
                    ),
                ),
                ("original_filename", models.CharField(blank=True, max_length=255)),
                ("size", models.PositiveBigIntegerField(default=0)),
                (
                    "extracted_text",
                    models.TextField(
                        blank=True,
                        help_text="Full text extracted for search indexing (async).",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="engine.source",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["source", "is_public"],
                        name="engine_sour_source__af1517_idx",
                    )
                ],
            },
        ),
        migrations.RunPython(copy_archived_files, restore_archived_files),
        migrations.RemoveField(
            model_name="source",
            name="archived_file",
        ),
        migrations.RemoveField(
            model_name="source",
            name="archived_file_hash",
        ),
    ]
