# Generated by Django 6.0.7 on 2026-07-21 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("engine", "0042_remove_source_archived_file_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostFurtherReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "position",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Display order within the Further Reading section.",
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        help_text="Optional note shown beneath the entry (why it's recommended).",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="further_reading",
                        to="engine.post",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="further_reading_entries",
                        to="engine.source",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
                "indexes": [
                    models.Index(
                        fields=["post", "position"],
                        name="engine_post_post_id_6dba91_idx",
                    )
                ],
                "unique_together": {("post", "source")},
            },
        ),
    ]
