# Generated by Django 6.0.8 on 2026-09-16 13:44

from django.db import migrations, models

import engine.markdown.dropcaps


class Migration(migrations.Migration):
    dependencies = [
        ("engine", "0044_page_markdown_authoring"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="dropcap_style",
            field=models.CharField(
                blank=True,
                choices=engine.markdown.dropcaps.document_dropcap_choices,
                default="",
                help_text="Dropcap style for the opening paragraph. Inherits the site default unless set; choose None to switch it off for this page.",
                max_length=40,
                verbose_name="Dropcap",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="dropcap_style",
            field=models.CharField(
                blank=True,
                choices=engine.markdown.dropcaps.document_dropcap_choices,
                default="",
                help_text="Dropcap style for the opening paragraph. Inherits the site default unless set; choose None to switch it off for this post.",
                max_length=40,
                verbose_name="Dropcap",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="default_dropcap_style",
            field=models.CharField(
                blank=True,
                choices=engine.markdown.dropcaps.site_dropcap_choices,
                default="",
                help_text="Dropcap style for the opening paragraph of every post and page. Off unless set; each post or page can override it.",
                max_length=40,
                verbose_name="Default dropcap",
            ),
        ),
    ]
